[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'cd client && npm ci --include=dev'
]

[phases.build]
cmds = [
  'cd client && npm run build',
  'cd server && npx prisma generate && npm run build'
]

[start]
cmd = 'cd server && npm start'

[variables]
NODE_ENV = 'production'